# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  encoder:
      class: AppBundle\Service\EncoderService
  unique.model.validator:
      class: AppBundle\Validator\Constraints\ModelExistValidator
      arguments:
          entityManager: "@doctrine.orm.entity_manager"
      tags:
           - { name: validator.constraint_validator, alias: unique.model.validator }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
